### ISSUE TITLE
calibration .yamlファイルが読み込まれない

### ISSUE THREAD

**Issue by ShunjiHashimoto** [ShunjiHashimoto/cugo#13]

**Comment by ShunjiHashimoto** [comment]
```bash
hashimoto@desktop:~/catkin_ws$ roslaunch cubase cubase.launch 
... logging to /home/hashimoto/.ros/log/713cad44-f898-11eb-8567-984827d817a0/roslaunch-desktop-12078.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://localhost:38249/

SUMMARY
========

PARAMETERS
 * /camera/camera_info_url: file:///home/hash...
 * /object_detection/bright_mn: 0
 * /object_detection/bright_mx: 0
 * /object_detection/hue_mn: 150
 * /object_detection/hue_mx: 179
 * /object_detection/sat_mn: 128
 * /object_detection/sat_mx: 255
 * /object_detection/value_mn: 0
 * /object_detection/value_mx: 255
 * /rosdistro: melodic
 * /rosversion: 1.14.11

NODES
  /
    camera (uvc_camera/uvc_camera_node)
    image_proc (image_proc/image_proc)
    object_detection (cugo_detection/object_detection)

auto-starting new master
process[master]: started with pid [12088]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 713cad44-f898-11eb-8567-984827d817a0
process[rosout-1]: started with pid [12099]
started core service [/rosout]
process[camera-2]: started with pid [12102]
process[image_proc-3]: started with pid [12107]
process[object_detection-4]: started with pid [12113]
[ WARN] [1628461919.048698739]: Camera calibration file did not specify distortion model, assuming plumb bob
[ WARN] [1628461919.048772070]: [camera] does not match name narrow_stereo in file /home/hashimoto/catkin_ws/src/cugo/cugo_teleop/config/camera.yaml
[ WARN] [1628461919.089799445]: Started in the global namespace! This is probably wrong. Start image_proc in the camera namespace.
Example command-line usage:
        $ ROS_NAMESPACE=my_camera rosrun image_proc image_proc
^C[object_detection-4] killing on exit
[image_proc-3] killing on exit
[camera-2] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

**Comment by ShunjiHashimoto** [comment]
```yaml
image_width: 640
image_height: 480
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [ 473.66338,    0.     ,  304.84389,
            0.     ,  476.26669,  201.08269,
            0.     ,    0.     ,    1.     ]
camera_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.151775, -0.165566, -0.000982, -0.002355, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 1.,  0.,  0.,
          0.,  1.,  0.,
          0.,  0.,  1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [ 490.11395,    0.     ,  303.29422,    0.     ,
            0.     ,  493.36469,  200.58533,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]

```

**Comment by ShunjiHashimoto** [comment]
```yaml
image_width: 640
image_height: 480
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [ 473.66338,    0.     ,  304.84389,
            0.     ,  476.26669,  201.08269,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.151775, -0.165566, -0.000982, -0.002355, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 1.,  0.,  0.,
          0.,  1.,  0.,
          0.,  0.,  1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [ 490.11395,    0.     ,  303.29422,    0.     ,
            0.     ,  493.36469,  200.58533,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]

```

**Comment by ShunjiHashimoto** [comment]
```yaml
image_width: 640
image_height: 480
camera_name: camera
camera_matrix:
  rows: 3
  cols: 3
  data: [ 473.66338,    0.     ,  304.84389,
            0.     ,  476.26669,  201.08269,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.151775, -0.165566, -0.000982, -0.002355, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 1.,  0.,  0.,
          0.,  1.,  0.,
          0.,  0.,  1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [ 490.11395,    0.     ,  303.29422,    0.     ,
            0.     ,  493.36469,  200.58533,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]

```
